// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vm0MsAYdd3oYojVcvKxNjp7M7-dc-LI',
    appId: '1:590002505820:web:5cfd6e8e80a1be98ed7e99',
    messagingSenderId: '590002505820',
    projectId: 'crud-9c3ab',
    authDomain: 'crud-9c3ab.firebaseapp.com',
    storageBucket: 'crud-9c3ab.appspot.com',
    measurementId: 'G-BK8B14CQ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG6jT4_gfXPc8uXRHhEIVyXbDR_khitPU',
    appId: '1:590002505820:android:8bfa779ea5b1c984ed7e99',
    messagingSenderId: '590002505820',
    projectId: 'crud-9c3ab',
    storageBucket: 'crud-9c3ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52pLuO7XvdSAjdHo4-kw-IZvaoErqsv8',
    appId: '1:590002505820:ios:3a91f42a5e4a46d0ed7e99',
    messagingSenderId: '590002505820',
    projectId: 'crud-9c3ab',
    storageBucket: 'crud-9c3ab.appspot.com',
    iosClientId: '590002505820-i14nkk92fj7gc3o2veb2esk9h8257rni.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52pLuO7XvdSAjdHo4-kw-IZvaoErqsv8',
    appId: '1:590002505820:ios:45401fca44c67511ed7e99',
    messagingSenderId: '590002505820',
    projectId: 'crud-9c3ab',
    storageBucket: 'crud-9c3ab.appspot.com',
    iosClientId: '590002505820-mf4gvr6mv64983r7dqarrrnkb7g8arg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCrud.RunnerTests',
  );
}
